# Generated by Django 2.1 on 2018-08-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='XXXXXXXXX', max_length=9, null=True),
        ),
    ]
