# Generated by Django 2.1 on 2018-08-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShop', '0003_auto_20180806_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
