# Generated by Django 2.1 on 2018-08-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShop', '0004_auto_20180806_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
