# Generated by Django 2.1 on 2018-08-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShop', '0005_book_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=99.99),
        ),
    ]
