# Generated by Django 2.1 on 2018-08-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShop', '0007_book_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_api',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book_api',
            name='price',
            field=models.FloatField(default=99.99),
        ),
    ]
