# Generated by Django 2.1 on 2018-08-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookShop', '0009_auto_20180811_0821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_api',
        ),
    ]
