# Generated by Django 2.1 on 2018-08-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookShop', '0010_delete_book_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
