# Generated by Django 2.1 on 2018-08-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=150)),
                ('director', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(choices=[('C', 'Current year'), ('O', 'Not current year'), ('TO', 'Too old not less than 1992')], default=2018)),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
