# Generated by Django 2.1 on 2018-08-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(choices=[('C', 'Current year'), ('O', 'Not current year'), ('TO', 'Too old not less than 1992')]),
        ),
    ]
