# Generated by Django 2.1 on 2018-08-04 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180804_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(upload_to='./songs/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movie', to='music.Album')),
            ],
        ),
    ]
